const companies = [
  {
    companyName: "Aranykorsó",
    location: "Budapest",
    registrationNumber: "38247839",
    vatNumber: "43534523",
    _id: "1",
    address: "Vasút utca 3",
    companyPhoneNumber: "0630-3334577",
    headquarters: "1125 Budapest, Vasút utca 3",
    billingAddress: "1125 Budapest, Vasút utca 3",
    category: "PUB",
    archived: false,
  },
  {
    companyName: "Stacy's food",
    location: "Budapest",
    registrationNumber: "38247839",
    vatNumber: "43534523",
    _id: "2",
    address: "",
    companyPhoneNumber: "",
    headquarters: "",
    billingAddress: "",
    category: "RESTAURANT",
    archived: false,
  },
  {
    companyName: "Aranykorsó",
    location: "Budapest",
    registrationNumber: "38247839",
    vatNumber: "43534523",
    _id: "3",
    address: "",
    companyPhoneNumber: "",
    headquarters: "",
    billingAddress: "",
    category: "BUFFET",
    archived: false,
  },
  {
    companyName: "Stacy's food",
    location: "Budapest",
    registrationNumber: "38247839",
    vatNumber: "43534523",
    _id: "4",
    address: "",
    companyPhoneNumber: "",
    headquarters: "",
    billingAddress: "",
    category: "PUB",
    archived: false,
  },
  {
    companyName: "Aranykorsó",
    location: "Budapest",
    registrationNumber: "38247839",
    vatNumber: "43534523",
    _id: "5",
    address: "",
    companyPhoneNumber: "",
    headquarters: "",
    billingAddress: "",
    category: "BUFFET",
    archived: false,
  },
  {
    companyName: "Stacy's food",
    location: "Budapest",
    registrationNumber: "38247839",
    vatNumber: "43534523",
    _id: "6",
    address: "",
    companyPhoneNumber: "",
    headquarters: "",
    billingAddress: "",
    category: "RESTAURANT",
    archived: false,
  },
];

module.exports = Object.freeze(companies);
